// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dot_net_assessment.Data;

#nullable disable

namespace dot_net_assessment.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20241011010959_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dot_net_assessment.Models.ManufacturingProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ManufacturingProcesses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8fe47fd-0b62-49ae-a229-2790ff04c4d9"),
                            Type = "Elaborado a mano"
                        },
                        new
                        {
                            Id = new Guid("d321ce3e-cd2f-4ce0-b8bd-16c28d06e13a"),
                            Type = "Elaborado a mano y a máquina"
                        });
                });

            modelBuilder.Entity("dot_net_assessment.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Dispatched")
                        .HasColumnType("bit");

                    b.Property<bool>("Faulty")
                        .HasColumnType("bit");

                    b.Property<Guid>("ManufacturingProcessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingProcessId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("dot_net_assessment.Models.Product", b =>
                {
                    b.HasOne("dot_net_assessment.Models.ManufacturingProcess", "ManufacturingProcess")
                        .WithMany()
                        .HasForeignKey("ManufacturingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManufacturingProcess");
                });
#pragma warning restore 612, 618
        }
    }
}
